name: Firebase Hosting Deploy

on:
  push:
    branches:
      - main  # Change to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Ensure this matches your project's Node.js version

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Build the React application
    - name: Build Application
      run: npm run build

    # Step 5: Deploy to Firebase Hosting
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        channelId: live
      env:
        PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
